### ISSUE TITLE
Instructions of Capstone Project!

### ISSUE THREAD

**Issue by sumairq** [sumairq/hollyflix-capstone#21]
# Hi There 👋 - Description of project
### Information of project:
- #### [GitHub Project Board link](https://github.com/sumairq/hollyflix-capstone/projects/1)
### Team members :
- #### @sumairq 
- #### @vanillainanutshell 
- #### @mukhammadrizooff

**Comment by elmar8287** [comment]
Hi team, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it.

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
