### ISSUE TITLE
Peer-to-peer-David-Dennis-Sam

### ISSUE THREAD

**Issue by denscholar** [sumairq/hollyflix-capstone#28]
Overall, you guys are doing a good job, especially with respect to the API you guys are working with. The animation is great. However, it could be nice if you improve on the styling of the buttons - comments, likes and reservations. 

I have nothing other than to say, congratulations and I wish you all the best.

<img src="https://media0.giphy.com/media/5hgYDDh5oqbmE4OKJ3/giphy.gif"/>

**Comment by mukhammadrizooff** [comment]
# @denscholar 
<img width="100%" src="https://media2.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif"/>
